4.Prime number 

import java.util.*;
public class Main
{
  public static void main (String[]args)
  {
	Scanner sc = new Scanner (System.in);
	  System.out.print ("Enter a number:");
	int number = sc.nextInt ();
	int count = 0;
	for (int i = 2; i <= number; i++)
	  {
		if (number % i == 0)
		  {
		  count++}
	  }
	if (count == 2)
	  {
		System.out.println ("Prime number");
	  }
	else
	  {
		System.out.println ("Not Prime number");
	  }


  }
}
