Numbers Programs:	

1. Swap 2 numbers without using the 3rd variable.
2. Even or odd numbers.
3. Leap year.
4. Prime number or not. 
5. Fibonacci Series.
6. Palindrome number or not.
7. Armstrong Number or not.
8. Reverse Number.
9. perfect square / Count Digits.
10. HCF OR GCD / LCM
11. Factorials number
12. Sum of digits
13. Find a Maximum of three numbers
14. Character is Vowel and consonant ( lowercase and uppercase).
